//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dogstar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dogstar.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files successfully validated..
        /// </summary>
        internal static string AllFilesValid {
            get {
                return ResourceManager.GetString("AllFilesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying precede {0}/{1}.
        /// </summary>
        internal static string ApplyingPrecede {
            get {
                return ResourceManager.GetString("ApplyingPrecede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Precede.
        /// </summary>
        internal static string ApplyPrecede {
            get {
                return ResourceManager.GetString("ApplyPrecede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to apply the precede patch now?.
        /// </summary>
        internal static string ApplyPrecedeNow {
            get {
                return ResourceManager.GetString("ApplyPrecedeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported proxy version..
        /// </summary>
        internal static string BadProxyVersion {
            get {
                return ResourceManager.GetString("BadProxyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked {0} of {1}.
        /// </summary>
        internal static string CheckedOf {
            get {
                return ResourceManager.GetString("CheckedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} of {1}.
        /// </summary>
        internal static string DownloadedOf {
            get {
                return ResourceManager.GetString("DownloadedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading English Patch....
        /// </summary>
        internal static string DownloadingEngPatch {
            get {
                return ResourceManager.GetString("DownloadingEngPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Japanese E-Codes....
        /// </summary>
        internal static string DownloadingJpECodes {
            get {
                return ResourceManager.GetString("DownloadingJpECodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Japanese Enemy Names....
        /// </summary>
        internal static string DownloadingJpEnemyNames {
            get {
                return ResourceManager.GetString("DownloadingJpEnemyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Large Files....
        /// </summary>
        internal static string DownloadingLargeFiles {
            get {
                return ResourceManager.GetString("DownloadingLargeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download In Progress.
        /// </summary>
        internal static string DownloadInProgress {
            get {
                return ResourceManager.GetString("DownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to download the latest preced?.
        /// </summary>
        internal static string DownloadLatestPreced {
            get {
                return ResourceManager.GetString("DownloadLatestPreced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter proxy JSON URL:.
        /// </summary>
        internal static string EnterProxy {
            get {
                return ResourceManager.GetString("EnterProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted {0} of {1}.
        /// </summary>
        internal static string ExtractedOf {
            get {
                return ResourceManager.GetString("ExtractedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed =&apos;^&apos;=.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files(s) were downloaded..
        /// </summary>
        internal static string FilesDownloaded {
            get {
                return ResourceManager.GetString("FilesDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogstar has detected the game directory, is this correct?.
        /// </summary>
        internal static string GameDetected {
            get {
                return ResourceManager.GetString("GameDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The servers are down for maintenance. You&apos;ll be unable to login. Continue anyway? .
        /// </summary>
        internal static string GameIsDown {
            get {
                return ResourceManager.GetString("GameIsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Update.
        /// </summary>
        internal static string GameUpdate {
            get {
                return ResourceManager.GetString("GameUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to PSO2 is available. Would you like to update?.
        /// </summary>
        internal static string GameUpdateAvailable {
            get {
                return ResourceManager.GetString("GameUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed to install..
        /// </summary>
        internal static string GenericPatchFailed {
            get {
                return ResourceManager.GetString("GenericPatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installed successfully..
        /// </summary>
        internal static string GenericPatchSuccess {
            get {
                return ResourceManager.GetString("GenericPatchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something appears to have gone wrong. Would you like to try again?.
        /// </summary>
        internal static string GoneWrong {
            get {
                return ResourceManager.GetString("GoneWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have PSO2 installed?.
        /// </summary>
        internal static string HaveInstalled {
            get {
                return ResourceManager.GetString("HaveInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game directory appears to be invalid. Would you like to try again?.
        /// </summary>
        internal static string InvalidPathTryAgain {
            get {
                return ResourceManager.GetString("InvalidPathTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string InvalidProxyURL {
            get {
                return ResourceManager.GetString("InvalidProxyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogstar will continue running to complete the download. Would you like to continue anyway?.
        /// </summary>
        internal static string LaunchDownloadInProgress {
            get {
                return ResourceManager.GetString("LaunchDownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find folder.
        /// </summary>
        internal static string MissingFolder {
            get {
                return ResourceManager.GetString("MissingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        internal static string Moved {
            get {
                return ResourceManager.GetString("Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game folder is unable to be found. Was it moved or deleted?.
        /// </summary>
        internal static string MovedOrDeleted {
            get {
                return ResourceManager.GetString("MovedOrDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer {0} is available. Would you like to update?.
        /// </summary>
        internal static string NewGenericPatch {
            get {
                return ResourceManager.GetString("NewGenericPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Language Patch.
        /// </summary>
        internal static string NewLangPatch {
            get {
                return ResourceManager.GetString("NewLangPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-JP PSO2 is incompatible with Dogstar. _(:３」∠)_.
        /// </summary>
        internal static string NonJPPSO2 {
            get {
                return ResourceManager.GetString("NonJPPSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing....
        /// </summary>
        internal static string Pausing {
            get {
                return ResourceManager.GetString("Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Precede Available.
        /// </summary>
        internal static string PrecedeAvailable {
            get {
                return ResourceManager.GetString("PrecedeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete precede folder. Try deleting it manually..
        /// </summary>
        internal static string PrecedeDeleteFailed {
            get {
                return ResourceManager.GetString("PrecedeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to proxy. Reverting changes..
        /// </summary>
        internal static string ProxyRevert {
            get {
                return ResourceManager.GetString("ProxyRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the location of pso2.exe.
        /// </summary>
        internal static string SelectExe {
            get {
                return ResourceManager.GetString("SelectExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an install location..
        /// </summary>
        internal static string SelectInstallLocation {
            get {
                return ResourceManager.GetString("SelectInstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string ServerMaintenance {
            get {
                return ResourceManager.GetString("ServerMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to install PSO2?.
        /// </summary>
        internal static string WouldYoulikeToInstall {
            get {
                return ResourceManager.GetString("WouldYoulikeToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
